{{- if .Values.deploy -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: {{ .Values.stack.service.type }}
  {{- if eq .Values.stack.service.type "LoadBalancer" }}
  loadBalancerIP: {{ .Values.stack.loadBalancerIP }}
  {{- end }}
  externalTrafficPolicy: Local
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.deployment.portName }}
  selector:
    app: {{ .Values.name }}
{{- end -}}
