deploy: true
trustedProxies: "192"
name: hegel
image: quay.io/tinkerbell/hegel:v0.10.1
imagePullPolicy: IfNotPresent
replicas: 1
service:
  port: 50061
  type: LoadBalancer
deployment:
  port: 50061
  portName: hegel-http
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
roleName: hegel-role
roleBindingName: hegel-rolebinding
loadBalancerIP: 192.168.2.111
  
